swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.1.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transactions API
      description: API for fetching user transactions on accountId for the current month
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: Bank account Id for transactions retrieve
          type: string
          required: true
      responses:
        '200':
          description: User transactions retrieved successully
          schema:
            $ref: '#/definitions/TransactionsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{accountId}/transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction Details API
      description: API for fetching specific user transaction on accountId
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: Bank account Id for transactions retrieve
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction Id to be given details
          required: true
          type: string
      responses:
        '200':
          description: User transaction details retrieved successully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction Informations (category & notes) update API
      description: API for updating specific transaction category or notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: Bank account Id for transactions retrieve
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction category / notes
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      responses:
        '200':
          description: User transaction updated successully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/{accountId}/transactions/{transactionId}/notes:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction Notes adding API
      description: API for creating specific transaction notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: Bank account Id for transactions retrieve
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
        - in: body
          name: body
          description: Update user transaction notes
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdateNotes'
      responses:
        '200':
          description: User transaction notes updated successully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Transaction Notes deleting API
      description: API for deleting specific transaction notes
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          description: Bank account Id for transactions retrieve
          required: true
          type: string
        - in: path
          name: transactionId
          description: Transaction Id to be updated
          required: true
          type: string
      responses:
        '200':
          description: User transaction notes deleted successully
          schema:
            $ref: '#/definitions/TransactionDetailsResponseDelete'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  TransactionsResponse:
    type: object
    properties:
      status:
        type: integer
        description: request response status
        example: 200
      message:
        type: string
        description: request response message
        example: "Request Processed Successfully"
      body:
        type: array
        items:
          type: object
          properties:
            transactionId:
              type: string
              description: transaction id
              example: "634d71c7ddabdd31149c19ac"
            amount:
              type: number
              description: transaction amount
              example: 145.53
            date:
              type: string
              description: transaction date
              example: "2022-10-17T15:16:23.434Z"
            description:
              type: string
              description: transaction description
              example: "Golden Sun Bakery"
            balance:
              type: number
              description: account balance
              example: 2082.79
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
        description: request response status
        example: 200
      message:
        type: string
        description: request response message
        example: "Request Processed Successfully"
      body:
        type: object
        properties:
          transactionId:
            type: string
            example: "634d71c7ddabdd31149c19ac"
          amount:
            type: number
            description: transaction amount
            example: 145.53
          date:
            type: string
            description: transaction date
            example: "2022-10-17T15:16:23.434Z"
          description:
            type: string
            description: transaction description
            example: "Golden Sun Bakery"
          balance:
            type: number
            description: account balance
            example: 2082.79
          transactiontype:
            type: string
            description: account balance
            example: "Electronic"
          category:
            type: string
            description: transaction category
            example: "food"
          notes:
            type: string
            description: transaction notes
            example: "eggs and cheese"
  TransactionDetailsResponseDelete:
    type: object
    properties:
      status:
        type: integer
        description: request response status
        example: 200
      message:
        type: string
        description: request response message
        example: "Request Processed Successfully"
      body:
        type: object
        properties:
          transactionId:
            type: string
            example: "634d71c7ddabdd31149c19ac"
          amount:
            type: number
            description: transaction amount
            example: 145.53
          date:
            type: string
            description: transaction date
            example: "2022-10-17T15:16:23.434Z"
          description:
            type: string
            description: transaction description
            example: "Golden Sun Bakery"
          balance:
            type: number
            description: account balance
            example: 2082.79
          transactiontype:
            type: string
            description: account balance
            example: "Electronic"
          category:
            type: string
            description: transaction category
            example: "food"
          notes:
            type: string
            description: transaction notes
            example: ""
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: transaction category
        example: "food"
      notes:
        type: string
        description: transaction notes
        example: "eggs and cheese"
  TransactionUpdateNotes:
    type: object
    properties:
      notes:
        type: string
        description: transaction notes
        example: "eggs and cheese"